name = "RandomizedDiagonalEstimation"
uuid = "b486003b-2967-4096-ab2f-8c2dcb397e23"
authors = ["Niclas Popp"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
